### ISSUE TITLE
Service script installed by qpid-cpp is not compatible with gentoo

### ISSUE THREAD

**Issue by chrisrichardson77** [fourceu/qpid-portage-overlay#4]
The service script shipped with qpid-cpp was (most probably) written specifically for a redhat-based system and does not work on gentoo. Some options to fix this:
- Ask the Qpid team very nicely if they would like to fix the issue
- Include a gentoo-specific script as a patch

**Comment by ssorj** [comment]
We would like to fix it!  If we can make the script generic, great.  If not, we can include variants for particular distros in the Qpid upstream.

**Comment by chrisrichardson77** [comment]
Great! I'll look out for it in the coming releases, presumably after 0.32.

**Comment by ssorj** [comment]
Chris, I'm afraid we don't have gentoo systems around, so we can't develop and test a fix.  Can you provide a gentoo-compatible initscript attached to a qpid jira?

**Comment by chrisrichardson77** [comment]
Sure, we have this on our backlog so should have something soon.
